name: Deploy Flask App on EC2

on:
  workflow_run:
    workflows: [Deploy Flask App with Terraform]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: ./outputs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Parse Terraform Outputs
        id: vars
        run: |
          DB_HOST=$(jq -r '.db_endpoint.value' ./outputs/terraform_outputs.json)
          EC2_IP=$(jq -r '.ec2_public_ip.value' ./outputs/terraform_outputs.json)
          ECR_REPO=$(jq -r '.ecr_repo_url.value' ./outputs/terraform_outputs.json)

          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV
          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 Python.pem

      - name: SSH into EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.EC2_IP }} << 'EOF'
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

            docker pull ${{ env.ECR_REPO }}:latest
            docker rm -f flask-app || true

            docker run -d --name flask-app -p 5001:5000 \
              -e DB_HOST=${{ env.DB_HOST }} \
              -e DB_NAME=greetings_db \
              -e DB_USER=${{ secrets.DB_USERNAME }} \
              -e DB_PASS=${{ secrets.DB_PASSWORD }} \
              ${{ env.ECR_REPO }}:latest
          EOF
